// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'theme_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ThemeConfigImpl _$$ThemeConfigImplFromJson(Map<String, dynamic> json) =>
    _$ThemeConfigImpl(
      id: json['id'] as String,
      configName: json['configName'] as String,
      isActive: json['isActive'] as bool,
      primaryColor: json['primaryColor'] as String,
      primaryLight: json['primaryLight'] as String,
      primaryDark: json['primaryDark'] as String,
      primarySurface: json['primarySurface'] as String,
      secondaryColor: json['secondaryColor'] as String,
      secondaryLight: json['secondaryLight'] as String,
      secondaryDark: json['secondaryDark'] as String,
      accentPink: json['accentPink'] as String,
      accentPurple: json['accentPurple'] as String,
      accentBlue: json['accentBlue'] as String,
      accentTeal: json['accentTeal'] as String,
      successColor: json['successColor'] as String,
      successLight: json['successLight'] as String,
      successDark: json['successDark'] as String,
      errorColor: json['errorColor'] as String,
      errorLight: json['errorLight'] as String,
      errorDark: json['errorDark'] as String,
      warningColor: json['warningColor'] as String,
      warningLight: json['warningLight'] as String,
      warningDark: json['warningDark'] as String,
      infoColor: json['infoColor'] as String,
      infoLight: json['infoLight'] as String,
      infoDark: json['infoDark'] as String,
      backgroundColor: json['backgroundColor'] as String,
      surfaceColor: json['surfaceColor'] as String,
      cardColor: json['cardColor'] as String,
      dividerColor: json['dividerColor'] as String,
      textPrimaryColor: json['textPrimaryColor'] as String,
      textSecondaryColor: json['textSecondaryColor'] as String,
      textDisabledColor: json['textDisabledColor'] as String,
      textOnPrimary: json['textOnPrimary'] as String,
      textOnSurface: json['textOnSurface'] as String,
      borderColor: json['borderColor'] as String,
      shadowColor: json['shadowColor'] as String,
      elevationShadow: json['elevationShadow'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      createdBy: json['createdBy'] as String?,
      version: (json['version'] as num).toInt(),
    );

Map<String, dynamic> _$$ThemeConfigImplToJson(_$ThemeConfigImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'configName': instance.configName,
      'isActive': instance.isActive,
      'primaryColor': instance.primaryColor,
      'primaryLight': instance.primaryLight,
      'primaryDark': instance.primaryDark,
      'primarySurface': instance.primarySurface,
      'secondaryColor': instance.secondaryColor,
      'secondaryLight': instance.secondaryLight,
      'secondaryDark': instance.secondaryDark,
      'accentPink': instance.accentPink,
      'accentPurple': instance.accentPurple,
      'accentBlue': instance.accentBlue,
      'accentTeal': instance.accentTeal,
      'successColor': instance.successColor,
      'successLight': instance.successLight,
      'successDark': instance.successDark,
      'errorColor': instance.errorColor,
      'errorLight': instance.errorLight,
      'errorDark': instance.errorDark,
      'warningColor': instance.warningColor,
      'warningLight': instance.warningLight,
      'warningDark': instance.warningDark,
      'infoColor': instance.infoColor,
      'infoLight': instance.infoLight,
      'infoDark': instance.infoDark,
      'backgroundColor': instance.backgroundColor,
      'surfaceColor': instance.surfaceColor,
      'cardColor': instance.cardColor,
      'dividerColor': instance.dividerColor,
      'textPrimaryColor': instance.textPrimaryColor,
      'textSecondaryColor': instance.textSecondaryColor,
      'textDisabledColor': instance.textDisabledColor,
      'textOnPrimary': instance.textOnPrimary,
      'textOnSurface': instance.textOnSurface,
      'borderColor': instance.borderColor,
      'shadowColor': instance.shadowColor,
      'elevationShadow': instance.elevationShadow,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
      'createdBy': instance.createdBy,
      'version': instance.version,
    };
