// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRzLOvUo0y8T28WJ9URR7oLTOa9Z0eR8',
    appId: '1:828054656956:android:9afbccbdb587f4d1553db9',
    messagingSenderId: '828054656956',
    projectId: 'sylonow-85de9',
    storageBucket: 'sylonow-85de9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_McA7Qycg0z9L4Vr6VsCa-gemSZYcn8s',
    appId: '1:828054656956:ios:bb5b36572f533867553db9',
    messagingSenderId: '828054656956',
    projectId: 'sylonow-85de9',
    storageBucket: 'sylonow-85de9.firebasestorage.app',
    androidClientId: '828054656956-b3slupq810c7dvlpln0ihh9bptk8b3fo.apps.googleusercontent.com',
    iosClientId: '828054656956-rr7l8n671eistd5o0cbjgn9smpgf2o39.apps.googleusercontent.com',
    iosBundleId: 'com.sylonow.vendor',
  );
}
