import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../../core/config/supabase_config.dart';
import '../models/theater_time_slot.dart';

part 'theater_time_slot_service.g.dart';

@riverpod
TheaterTimeSlotService theaterTimeSlotService(TheaterTimeSlotServiceRef ref) {
  return TheaterTimeSlotService();
}

class TheaterTimeSlotService {
  final _client = SupabaseConfig.client;

  // Get time slots for a specific theater screen
  Future<List<TheaterTimeSlot>> getScreenTimeSlots(String screenId) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Fetching time slots for screen: $screenId');
      
      final response = await _client
          .from('theater_time_slots')
          .select('*')
          .eq('screen_id', screenId)
          .eq('is_active', true)
          .order('start_time', ascending: true);

// TODO: Replace with proper logging - print('🔍 DEBUG: Time slots response: $response');

      if (response.isEmpty) {
        return [];
      }

      return response
          .map<TheaterTimeSlot>((data) => TheaterTimeSlot.fromJson(data))
          .toList();
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to fetch time slots: $e');
      rethrow;
    }
  }

  // Get time slots for a specific theater (all screens)
  Future<List<TheaterTimeSlot>> getTheaterTimeSlots(String theaterId) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Fetching time slots for theater: $theaterId');
      
      final response = await _client
          .from('theater_time_slots')
          .select('*')
          .eq('theater_id', theaterId)
          .eq('is_active', true)
          .order('start_time', ascending: true);

// TODO: Replace with proper logging - print('🔍 DEBUG: Theater time slots response: $response');

      if (response.isEmpty) {
        return [];
      }

      return response
          .map<TheaterTimeSlot>((data) => TheaterTimeSlot.fromJson(data))
          .toList();
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to fetch theater time slots: $e');
      rethrow;
    }
  }

  // Create a new time slot
  Future<TheaterTimeSlot> createTimeSlot(TheaterTimeSlot timeSlot) async {
    try {
      final slotData = timeSlot.toJson();
      
      // Remove fields that should not be sent on creation (auto-generated by DB)
      slotData.remove('id');
      slotData.remove('created_at');
      slotData.remove('updated_at');
      
// TODO: Replace with proper logging - print('🔍 DEBUG: Creating time slot: $slotData');
      
      final response = await _client
          .from('theater_time_slots')
          .insert(slotData)
          .select()
          .single();

// TODO: Replace with proper logging - print('🔍 DEBUG: Created time slot response: $response');
      return TheaterTimeSlot.fromJson(response);
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to create time slot: $e');
      rethrow;
    }
  }

  // Update time slot
  Future<TheaterTimeSlot> updateTimeSlot(String slotId, Map<String, dynamic> updates) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Updating time slot $slotId with: $updates');
      
      final response = await _client
          .from('theater_time_slots')
          .update(updates)
          .eq('id', slotId)
          .select()
          .single();

// TODO: Replace with proper logging - print('🔍 DEBUG: Updated time slot response: $response');
      return TheaterTimeSlot.fromJson(response);
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to update time slot: $e');
      rethrow;
    }
  }

  // Delete time slot
  Future<void> deleteTimeSlot(String slotId) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Deleting time slot: $slotId');
      
      await _client
          .from('theater_time_slots')
          .delete()
          .eq('id', slotId);

// TODO: Replace with proper logging - print('🔍 DEBUG: Time slot deleted successfully');
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to delete time slot: $e');
      rethrow;
    }
  }

  // Toggle time slot availability
  Future<TheaterTimeSlot> toggleSlotAvailability(String slotId, bool isAvailable) async {
    try {
      return await updateTimeSlot(slotId, {'is_available': isAvailable});
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to toggle slot availability: $e');
      rethrow;
    }
  }

  // Get all available time slots for a screen (recurring slots)
  Future<List<TheaterTimeSlot>> getAvailableSlots({
    required String screenId,
  }) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Fetching available slots for screen $screenId');
      
      final response = await _client
          .from('theater_time_slots')
          .select('*')
          .eq('screen_id', screenId)
          .eq('is_available', true)
          .eq('is_active', true)
          .order('start_time', ascending: true);

// TODO: Replace with proper logging - print('🔍 DEBUG: Available slots response: $response');

      if (response.isEmpty) {
        return [];
      }

      return response
          .map<TheaterTimeSlot>((data) => TheaterTimeSlot.fromJson(data))
          .toList();
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to fetch available slots: $e');
      rethrow;
    }
  }

  // Mark time slot as booked for a specific date
  Future<void> markSlotAsBooked(String slotId, DateTime date) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Marking slot $slotId as booked for date: $date');
      
      final bookingData = {
        'time_slot_id': slotId,
        'booked_date': date.toIso8601String().split('T')[0], // Format as YYYY-MM-DD
      };
      
      await _client
          .from('theater_time_slot_bookings')
          .insert(bookingData);

// TODO: Replace with proper logging - print('🔍 DEBUG: Time slot marked as booked successfully');
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to mark slot as booked: $e');
      rethrow;
    }
  }

  // Remove booking for a time slot (unmark as booked)
  Future<void> unmarkSlotAsBooked(String slotId) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Removing booking for slot: $slotId');
      
      await _client
          .from('theater_time_slot_bookings')
          .delete()
          .eq('time_slot_id', slotId);

// TODO: Replace with proper logging - print('🔍 DEBUG: Booking removed successfully');
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to remove booking: $e');
      rethrow;
    }
  }

  // Remove booking for a time slot on a specific date
  Future<void> unmarkSlotAsBookedForDate(String slotId, DateTime date) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Removing booking for slot $slotId on date: $date');
      final dateStr = date.toIso8601String().split('T')[0];
      
      // Remove from theater_time_slot_bookings table
      await _client
          .from('theater_time_slot_bookings')
          .delete()
          .eq('time_slot_id', slotId)
          .eq('booked_date', dateStr);

      // Note: We don't delete from private_theater_bookings as those are actual customer bookings
      // and should only be cancelled through proper booking management, not through time slot management
      
// TODO: Replace with proper logging - print('🔍 DEBUG: Booking removed successfully for specific date');
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to remove booking for date: $e');
      rethrow;
    }
  }

  // Check if a time slot is booked for a specific date
  Future<bool> isSlotBookedForDate(String slotId, DateTime date) async {
    try {
      final dateStr = date.toIso8601String().split('T')[0];
      
      // Check theater_time_slot_bookings table
      final timeSlotBookingResponse = await _client
          .from('theater_time_slot_bookings')
          .select('id')
          .eq('time_slot_id', slotId)
          .eq('booked_date', dateStr)
          .maybeSingle();

      if (timeSlotBookingResponse != null) {
        return true;
      }

      // Check private_theater_bookings table
      final privateBookingResponse = await _client
          .from('private_theater_bookings')
          .select('id')
          .eq('time_slot_id', slotId)
          .eq('booking_date', dateStr)
          .neq('booking_status', 'cancelled') // Exclude cancelled bookings
          .maybeSingle();

      return privateBookingResponse != null;
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to check if slot is booked: $e');
      return false;
    }
  }

  // Get all booked dates for a time slot
  Future<List<DateTime>> getBookedDatesForSlot(String slotId) async {
    try {
      final Set<DateTime> bookedDates = {};

      // Get dates from theater_time_slot_bookings table
      final timeSlotBookingsResponse = await _client
          .from('theater_time_slot_bookings')
          .select('booked_date')
          .eq('time_slot_id', slotId)
          .order('booked_date', ascending: true);

      for (final data in timeSlotBookingsResponse) {
        bookedDates.add(DateTime.parse(data['booked_date']));
      }

      // Get dates from private_theater_bookings table
      final privateBookingsResponse = await _client
          .from('private_theater_bookings')
          .select('booking_date')
          .eq('time_slot_id', slotId)
          .neq('booking_status', 'cancelled') // Exclude cancelled bookings
          .order('booking_date', ascending: true);

      for (final data in privateBookingsResponse) {
        bookedDates.add(DateTime.parse(data['booking_date']));
      }

      // Return sorted list of unique dates
      final sortedDates = bookedDates.toList()..sort();
      return sortedDates;
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to get booked dates: $e');
      return [];
    }
  }

  // Get detailed booking information for a time slot on a specific date
  Future<Map<String, dynamic>?> getBookingDetailsForSlotAndDate(String slotId, DateTime date) async {
    try {
      final dateStr = date.toIso8601String().split('T')[0];
      
      // Check theater_time_slot_bookings table first (vendor-marked bookings)
      final timeSlotBookingResponse = await _client
          .from('theater_time_slot_bookings')
          .select('*')
          .eq('time_slot_id', slotId)
          .eq('booked_date', dateStr)
          .maybeSingle();

      if (timeSlotBookingResponse != null) {
        return {
          'type': 'vendor_booking',
          'data': timeSlotBookingResponse,
          'can_unbook': true, // Vendor can remove their own markings
        };
      }

      // Check private_theater_bookings table (customer bookings)
      final privateBookingResponse = await _client
          .from('private_theater_bookings')
          .select('*, user_id')
          .eq('time_slot_id', slotId)
          .eq('booking_date', dateStr)
          .neq('booking_status', 'cancelled')
          .maybeSingle();

      if (privateBookingResponse != null) {
        return {
          'type': 'customer_booking',
          'data': privateBookingResponse,
          'can_unbook': false, // Customer bookings should not be removed from time slot management
          'customer_name': privateBookingResponse['contact_name'],
          'booking_status': privateBookingResponse['booking_status'],
        };
      }

      return null; // No booking found
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to get booking details: $e');
      return null;
    }
  }

  // Check if a time slot with overlapping times already exists for the given screen
  // Returns null if no overlap, otherwise returns information about overlapping slots
  Future<Map<String, dynamic>?> checkTimeSlotOverlap(String screenId, String startTime, String endTime, {String? excludeSlotId}) async {
    try {
// TODO: Replace with proper logging - print('🔍 DEBUG: Checking if overlapping time slot exists for screen $screenId: $startTime - $endTime');
      
      // Get all existing time slots for this screen
      var query = _client
          .from('theater_time_slots')
          .select('id, start_time, end_time')
          .eq('screen_id', screenId)
          .eq('is_active', true);
      
      if (excludeSlotId != null) {
        query = query.neq('id', excludeSlotId);
      }
      
      final response = await query;
      
      // Check for overlapping time slots
      final overlappingSlots = <Map<String, dynamic>>[];
      for (final slot in response) {
        final existingStart = slot['start_time'] as String;
        final existingEnd = slot['end_time'] as String;
        
        // Check if the new time slot overlaps with existing one
        if (_isTimeOverlapping(startTime, endTime, existingStart, existingEnd)) {
          overlappingSlots.add({
            'start_time': existingStart,
            'end_time': existingEnd,
          });
        }
      }
      
      if (overlappingSlots.isNotEmpty) {
// TODO: Replace with proper logging - print('🔍 DEBUG: Overlapping time slots found: $overlappingSlots');
        return {
          'has_overlap': true,
          'overlapping_slots': overlappingSlots,
        };
      }
      
// TODO: Replace with proper logging - print('🔍 DEBUG: No overlapping time slots found');
      return null;
    } catch (e) {
// TODO: Replace with proper logging - print('🔴 ERROR: Failed to check if time slot exists: $e');
      return null;
    }
  }

  // Legacy method for backward compatibility
  Future<bool> isTimeSlotExists(String screenId, String startTime, String endTime, {String? excludeSlotId}) async {
    final result = await checkTimeSlotOverlap(screenId, startTime, endTime, excludeSlotId: excludeSlotId);
    return result != null;
  }

     // Helper method to check if two time ranges overlap (strict blocking)
   bool _isTimeOverlapping(String start1, String end1, String start2, String end2) {
     // Convert time strings to minutes for easier comparison
     final start1Minutes = _timeStringToMinutes(start1);
     final end1Minutes = _timeStringToMinutes(end1);
     final start2Minutes = _timeStringToMinutes(start2);
     final end2Minutes = _timeStringToMinutes(end2);
     
     // Strict blocking: any overlap is not allowed
     // This includes:
     // 1. New slot starts before existing ends AND new slot ends after existing starts
     // 2. New slot starts exactly when existing ends (not allowed)
     // 3. New slot ends exactly when existing starts (not allowed)
     // 4. New slot completely contains existing slot
     // 5. Existing slot completely contains new slot
     
     return start1Minutes < end2Minutes && end1Minutes > start2Minutes ||
            start1Minutes == end2Minutes ||
            end1Minutes == start2Minutes;
   }

   // Helper method to convert time string (HH:MM) to minutes
   int _timeStringToMinutes(String timeString) {
     final parts = timeString.split(':');
     final hours = int.parse(parts[0]);
     final minutes = int.parse(parts[1]);
     return hours * 60 + minutes;
   }
 }